//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5448.
// 
#pragma warning disable 1591

namespace WindowsFormsApplication1.localhost {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="carwsBinding", Namespace="urn:carws")]
    public partial class carws : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback carOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public carws() {
            this.Url = global::WindowsFormsApplication1.Properties.Settings.Default.WindowsFormsApplication1_localhost_carws;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event carCompletedEventHandler carCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:carws#car", RequestNamespace="urn:carws", ResponseNamespace="urn:carws")]
        [return: System.Xml.Serialization.SoapElementAttribute("reply")]
        public reply car([System.Xml.Serialization.SoapElementAttribute("Car")] Car Car1) {
            object[] results = this.Invoke("car", new object[] {
                        Car1});
            return ((reply)(results[0]));
        }
        
        /// <remarks/>
        public void carAsync(Car Car1) {
            this.carAsync(Car1, null);
        }
        
        /// <remarks/>
        public void carAsync(Car Car1, object userState) {
            if ((this.carOperationCompleted == null)) {
                this.carOperationCompleted = new System.Threading.SendOrPostCallback(this.OncarOperationCompleted);
            }
            this.InvokeAsync("car", new object[] {
                        Car1}, this.carOperationCompleted, userState);
        }
        
        private void OncarOperationCompleted(object arg) {
            if ((this.carCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.carCompleted(this, new carCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:carws")]
    public partial class Car {
        
        private int makerField;
        
        private string modelField;
        
        private int min_priceField;
        
        private int max_priceField;
        
        private int min_engineField;
        
        private int max_engineField;
        
        private int min_powerField;
        
        private int max_powerField;
        
        private int min_kmField;
        
        private int max_kmField;
        
        private int min_yearField;
        
        private int max_yearField;
        
        private string colorField;
        
        /// <remarks/>
        public int maker {
            get {
                return this.makerField;
            }
            set {
                this.makerField = value;
            }
        }
        
        /// <remarks/>
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public int min_price {
            get {
                return this.min_priceField;
            }
            set {
                this.min_priceField = value;
            }
        }
        
        /// <remarks/>
        public int max_price {
            get {
                return this.max_priceField;
            }
            set {
                this.max_priceField = value;
            }
        }
        
        /// <remarks/>
        public int min_engine {
            get {
                return this.min_engineField;
            }
            set {
                this.min_engineField = value;
            }
        }
        
        /// <remarks/>
        public int max_engine {
            get {
                return this.max_engineField;
            }
            set {
                this.max_engineField = value;
            }
        }
        
        /// <remarks/>
        public int min_power {
            get {
                return this.min_powerField;
            }
            set {
                this.min_powerField = value;
            }
        }
        
        /// <remarks/>
        public int max_power {
            get {
                return this.max_powerField;
            }
            set {
                this.max_powerField = value;
            }
        }
        
        /// <remarks/>
        public int min_km {
            get {
                return this.min_kmField;
            }
            set {
                this.min_kmField = value;
            }
        }
        
        /// <remarks/>
        public int max_km {
            get {
                return this.max_kmField;
            }
            set {
                this.max_kmField = value;
            }
        }
        
        /// <remarks/>
        public int min_year {
            get {
                return this.min_yearField;
            }
            set {
                this.min_yearField = value;
            }
        }
        
        /// <remarks/>
        public int max_year {
            get {
                return this.max_yearField;
            }
            set {
                this.max_yearField = value;
            }
        }
        
        /// <remarks/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:carws")]
    public partial class reply {
        
        private string reply0Field;
        
        /// <remarks/>
        public string reply0 {
            get {
                return this.reply0Field;
            }
            set {
                this.reply0Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void carCompletedEventHandler(object sender, carCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class carCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal carCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public reply Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((reply)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591