//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3625.
// 
namespace carz.localhost2 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="modelwsBinding", Namespace="urn:modelws")]
    public partial class modelws : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public modelws() {
            this.Url = "http://web2.teiser.gr/webservices/ws_model/modelws.php";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:modelws#models", RequestNamespace="urn:modelws", ResponseNamespace="urn:modelws")]
        [return: System.Xml.Serialization.SoapElementAttribute("reply")]
        public reply models(Maker Maker) {
            object[] results = this.Invoke("models", new object[] {
                        Maker});
            return ((reply)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginmodels(Maker Maker, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("models", new object[] {
                        Maker}, callback, asyncState);
        }
        
        /// <remarks/>
        public reply Endmodels(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((reply)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:modelws")]
    public partial class Maker {
        
        private int makerField;
        
        /// <remarks/>
        public int maker {
            get {
                return this.makerField;
            }
            set {
                this.makerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:modelws")]
    public partial class reply {
        
        private string reply0Field;
        
        /// <remarks/>
        public string reply0 {
            get {
                return this.reply0Field;
            }
            set {
                this.reply0Field = value;
            }
        }
    }
}
