//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3625.
// 
namespace carz.localhost {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="carwsBinding", Namespace="urn:carws")]
    public partial class carws : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public carws() {
            this.Url = "http://web2.teiser.gr/webservices/ws/carws.php";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:carws#car", RequestNamespace="urn:carws", ResponseNamespace="urn:carws")]
        [return: System.Xml.Serialization.SoapElementAttribute("reply")]
        public reply car([System.Xml.Serialization.SoapElementAttribute("Car")] Car Car1) {
            object[] results = this.Invoke("car", new object[] {
                        Car1});
            return ((reply)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begincar(Car Car1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("car", new object[] {
                        Car1}, callback, asyncState);
        }
        
        /// <remarks/>
        public reply Endcar(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((reply)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:carws")]
    public partial class Car {
        
        private int makerField;
        
        private string modelField;
        
        private int min_priceField;
        
        private int max_priceField;
        
        private int min_engineField;
        
        private int max_engineField;
        
        private int min_powerField;
        
        private int max_powerField;
        
        private int min_kmField;
        
        private int max_kmField;
        
        private int min_yearField;
        
        private int max_yearField;
        
        private string colorField;
        
        /// <remarks/>
        public int maker {
            get {
                return this.makerField;
            }
            set {
                this.makerField = value;
            }
        }
        
        /// <remarks/>
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public int min_price {
            get {
                return this.min_priceField;
            }
            set {
                this.min_priceField = value;
            }
        }
        
        /// <remarks/>
        public int max_price {
            get {
                return this.max_priceField;
            }
            set {
                this.max_priceField = value;
            }
        }
        
        /// <remarks/>
        public int min_engine {
            get {
                return this.min_engineField;
            }
            set {
                this.min_engineField = value;
            }
        }
        
        /// <remarks/>
        public int max_engine {
            get {
                return this.max_engineField;
            }
            set {
                this.max_engineField = value;
            }
        }
        
        /// <remarks/>
        public int min_power {
            get {
                return this.min_powerField;
            }
            set {
                this.min_powerField = value;
            }
        }
        
        /// <remarks/>
        public int max_power {
            get {
                return this.max_powerField;
            }
            set {
                this.max_powerField = value;
            }
        }
        
        /// <remarks/>
        public int min_km {
            get {
                return this.min_kmField;
            }
            set {
                this.min_kmField = value;
            }
        }
        
        /// <remarks/>
        public int max_km {
            get {
                return this.max_kmField;
            }
            set {
                this.max_kmField = value;
            }
        }
        
        /// <remarks/>
        public int min_year {
            get {
                return this.min_yearField;
            }
            set {
                this.min_yearField = value;
            }
        }
        
        /// <remarks/>
        public int max_year {
            get {
                return this.max_yearField;
            }
            set {
                this.max_yearField = value;
            }
        }
        
        /// <remarks/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:carws")]
    public partial class reply {
        
        private string reply0Field;
        
        /// <remarks/>
        public string reply0 {
            get {
                return this.reply0Field;
            }
            set {
                this.reply0Field = value;
            }
        }
    }
}
